server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #          uri: file:///Users/dowonlee/Desktop/Work/git-local-repo
          uri: https://github.com/JeonSalmong/spring-cloud-config
        #          basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
        #          username: [username]
        #          password: [password]
        native:
          search-locations: C:\Users\DCCIS067000\Documents\GitHub\spring-cloud-config